[package]
name = "barbados"
version = "0.1.0"
edition = "2021"

[dependencies]
async-channel = "1.7.1"
tokio = { version = "1.20.1", features = ["rt", "sync"] }

[dev-dependencies]
tokio = { version = "1.20.1", features = ["macros", "time"] }
